"""Unit 3 notes examples moved into the videos (2026-10-01). Run once: python tools/specs_unit3.py"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from add_video_example import apply  # noqa: E402

SPECS = [
    dict(num="3.1", title="Trig and exponential", after="Function notation says where",
         problem=r"Find (a) $\dfrac{d}{dx}\sin(3x)$ and (b) $\dfrac{d}{dx}e^{x^2}$.",
         steps=[r"\text{(a) } u = 3x,\ u' = 3: \quad \cos(3x)\cdot 3 = 3\cos(3x)", r"\text{(b) } u = x^2,\ u' = 2x: \quad e^{x^2}\cdot 2x = 2xe^{x^2}"], at=[1, 2],
         lines=["Find the derivatives of sine of three x, and of e to the x squared. [try it]",
                "For sine of three x, the inside is u equals three x, with u prime three. Cosine of the inside, times three: three cosine three x. [pause]",
                "For e to the x squared, the inside is u equals x squared, with u prime two x. e to the x squared, times two x. [long pause]"],
         screen="Each part with its inside u and u′ named, then f′(u) · u′ written out.",
         checks=["diff(sin(3*x), x) == 3*cos(3*x)", "diff(exp(x**2), x) == 2*x*exp(x**2)"], work="2.2cm"),
    dict(num="3.1", title="A root", after="Trig and exponential",
         problem=r"Find $\dfrac{d}{dx}\sqrt{1 + \cos x}$.",
         steps=[r"u = 1 + \cos x, \quad u' = -\sin x", r"\left[\sqrt{u}\right]' = \frac{1}{2\sqrt{u}}\cdot u'", r"= \frac{1}{2\sqrt{1 + \cos x}}\cdot(-\sin x) = -\frac{\sin x}{2\sqrt{1 + \cos x}}"],
         at=[1, 2, 3],
         lines=["Find the derivative of the square root of one plus cosine x. [try it]",
                "The inside is u equals one plus cosine x, and u prime is negative sine x.",
                "The outside is a square root, whose derivative is one over two root u. Times u prime. [pause]",
                "So the derivative is negative sine x, over two times the square root of one plus cosine x. [long pause]"],
         screen="u and u′ named, the square-root rule with u inside, and the simplified result.",
         checks=["simplify(diff(sqrt(1 + cos(x)), x) + sin(x)/(2*sqrt(1 + cos(x)))) == 0"], work="2.4cm"),
    dict(num="3.3", title="From a table", after="The trap",
         problem=r"$g$ is invertible. Use the table to find $\left(g^{-1}\right)'(4)$.",
         pre='gtab = table(["x", "g(x)", "g\'(x)"], [["1", "4", "3"], ["4", "6", r"\\tfrac12"]], size=38)',
         steps=[r"g(1) = 4: \ \text{the matching point is } x = 1", r"\left(g^{-1}\right)'(4) = \frac{1}{g'(1)} = \frac13", r"TEXT:Not $\frac{1}{g'(4)}$: the $4$ is an output of $g$."],
         at=[1, 2, 3], extra="figure=gtab",
         lines=["g is invertible. Use the table to find the derivative of g inverse at four. [try it]",
                "Four is an output of g, so find where g equals four. That's at x equals one.",
                "The inverse's slope is one over g prime of one: one third. [pause]",
                "The trap would be g prime of four. The four belongs to the inverse, not to g. [long pause]"],
         screen="The table x = 1, 4; g = 4, 6; g′ = 3, 1/2. The output 4 in the g column is circled, pointing to x = 1, and 1/g′(1) = 1/3.",
         work="2cm"),
    dict(num="3.3", title="The natural log, again", after="Implicit differentiation agrees",
         problem=r"Use $\ln x$ as the inverse of $e^x$ to find $\dfrac{d}{dx}\ln x$.",
         steps=[r"y = \ln x \ \Rightarrow\ e^y = x", r"e^y\,\frac{dy}{dx} = 1", r"\frac{dy}{dx} = \frac{1}{e^y} = \frac{1}{x}"], at=[1, 2, 3],
         lines=["Use the natural log as the inverse of e to the x to find its derivative. [try it]",
                "If y is the natural log of x, then e to the y equals x.",
                "Differentiate implicitly: e to the y, times d y d x, equals one. [pause]",
                "So d y d x is one over e to the y. And e to the y is x, so the derivative is one over x, just as we found before. [long pause]"],
         screen="y = ln x rewritten as e^y = x, differentiated implicitly, and solved: dy/dx = 1/e^y = 1/x.",
         work="2cm"),
    dict(num="3.4", title="Arcsine with the chain rule", after="The family", notes_title="With the chain rule",
         problem=r"Find $\dfrac{d}{dx}\arctan(3x)$ and $\dfrac{d}{dx}\arcsin\left(x^2\right)$.",
         steps=[r"u = 3x,\ u' = 3: \quad \frac{1}{1 + u^2}\cdot u' = \frac{3}{1 + 9x^2}", r"u = x^2,\ u' = 2x: \quad \frac{1}{\sqrt{1 - u^2}}\cdot u' = \frac{2x}{\sqrt{1 - x^4}}"],
         at=[1, 2],
         lines=["Find the derivatives of arctangent of three x and arcsine of x squared. [try it]",
                "For arctangent of three x, u is three x. One over one plus u squared, times u prime: three over one plus nine x squared. [pause]",
                "For arcsine of x squared, u is x squared. One over the square root of one minus u squared, times two x: two x over the square root of one minus x to the fourth. [long pause]"],
         screen="Each inverse-trig rule written with u, then u and u′ substituted.",
         checks=["simplify(diff(asin(x**2), x) - 2*x/sqrt(1 - x**4)) == 0"], work="2.2cm"),
    dict(num="3.5", title="Layers", after="Then repeat inside",
         problem=r"Find $\dfrac{d}{dx}\left[x^2\sin(3x)\right]$.",
         steps=[r"\text{last operation: a product } \underbrace{x^2}_{u}\,\underbrace{\sin(3x)}_{v}", r"u' = 2x, \qquad v' = \cos(3x)\cdot 3",
                r"u'v + uv' = 2x\sin(3x) + 3x^2\cos(3x)"], at=[1, 2, 3],
         lines=["Find the derivative of x squared times sine of three x. [try it]",
                "The last operation is a multiplication, so start with the product rule: u is x squared, v is sine three x.",
                "u prime is two x. v prime needs the chain rule: cosine three x, times three. [pause]",
                "Put it together: two x sine three x, plus three x squared cosine three x. [long pause]"],
         screen="The last operation identified as a product, u and v labeled, v′ found with the chain rule, and u′v + uv′ assembled.",
         checks=["diff(x**2*sin(3*x), x) == 2*x*sin(3*x) + 3*x**2*cos(3*x)"], work="2.2cm"),
    dict(num="3.5", title="Rewrite first", after="Rewrite before you start",
         problem=r"Find $\dfrac{d}{dx}\left[\dfrac{x^3 - 2\sqrt x}{x}\right]$.",
         steps=[r"\frac{x^3 - 2x^{1/2}}{x} = x^2 - 2x^{-1/2}", r"\frac{d}{dx}\left[x^2 - 2x^{-1/2}\right] = 2x + x^{-3/2}", r"TEXT:Much shorter than the quotient rule."],
         at=[1, 2, 3],
         lines=["Find the derivative of x cubed minus two root x, all over x. [try it]",
                "The bottom is a single term, so divide first: x squared minus two x to the negative one half.",
                "Now the power rule on each term: two x, plus x to the negative three halves. [pause]",
                "That's much shorter than the quotient rule. [long pause]"],
         screen="The fraction split over its single-term denominator, then the power rule on each term.",
         checks=["simplify(diff((x**3 - 2*sqrt(x))/x, x) - (2*x + x**Rational(-3, 2))) == 0"], work="2.2cm"),
]

if __name__ == "__main__":
    apply(SPECS)
