"""Unit 1 notes examples moved into the videos (2026-10-01). Run once: python tools/specs_unit1.py"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from add_video_example import apply  # noqa: E402

SPECS = [
    # ------------------------------------------------------------------ 1.1
    dict(num="1.1", title="Two average velocities", after="Average velocity", notes_title="Average velocity",
         problem=r"The arrow's position is $s(t) = 60t - 12t^2$ meters. Find its average velocity (a) from $t = 0$ to $t = 2$ and (b) from $t = 1$ to $t = 2$.",
         steps=[r"s(0) = 0, \quad s(1) = 48, \quad s(2) = 72", r"\text{(a) } \frac{s(2) - s(0)}{2 - 0} = \frac{72 - 0}{2} = 36 \text{ m/s}",
                r"\text{(b) } \frac{s(2) - s(1)}{2 - 1} = \frac{72 - 48}{1} = 24 \text{ m/s}", r"TEXT:The arrow is slowing down, so its later average is smaller."],
         at=[1, 2, 3, 4],
         lines=["Find the arrow's average velocity from t equals zero to two, and then from t equals one to two. [try it]",
                "First the positions. s of zero is zero, s of one is forty-eight, and s of two is seventy-two.",
                "From zero to two: seventy-two minus zero, over two. Thirty-six meters per second. [pause]",
                "From one to two: seventy-two minus forty-eight, over one. Twenty-four meters per second.",
                "The arrow is slowing down, so its average over the later second is smaller. [long pause]"],
         screen="The problem, then the three positions, then each average velocity as change in position over change in time.",
         checks=["(60*2 - 12*4 - 0)/2 == 36", "(60*2 - 12*4) - (60 - 12) == 24"], work="3cm"),
    dict(num="1.1", title="A sprinter", after="An average isn't an instant",
         problem=r"A sprinter's distance $D(t)$, in meters, $t$ seconds after the start is in the table. Estimate the sprinter's speed at $t = 2$ seconds.",
         pre='sprint = table(["t", "0", "1", "2", "3", "4"], [["D(t)", "0", "3", "9", "17", "26"]], size=38)',
         steps=[r"\text{shortest interval with } t = 2 \text{ in the middle: } [1, 3]", r"\frac{D(3) - D(1)}{3 - 1} = \frac{17 - 3}{2} = 7 \text{ m/s}"],
         at=[1, 2],
         extra=r'''figure=sprint, text=r"A sprinter's distance $D(t)$ in meters, $t$ seconds after the start: \par\smallskip\centerline{\begin{tabular}{c|ccccc} $t$ (s) & 0 & 1 & 2 & 3 & 4 \\ \hline $D(t)$ (m) & 0 & 3 & 9 & 17 & 26 \end{tabular}} \par Estimate the sprinter's speed at $t = 2$ seconds."''',
         lines=["Here's a sprinter's distance at each second. Estimate the speed at two seconds. [try it]",
                "We can't shrink the interval below the data, so use the shortest interval with two in the middle: one to three seconds. [pause]",
                "Seventeen minus three, over three minus one: fourteen over two. About seven meters per second. [long pause]"],
         screen="The sprinter's table: t = 0 to 4, D = 0, 3, 9, 17, 26. The columns t = 1 and t = 3 light up, and (17 − 3)/(3 − 1) = 7 m/s.",
         checks=["Rational(17 - 3, 2) == 7"]),
    # ------------------------------------------------------------------ 1.2
    dict(num="1.2", title="Reading a graph", after="The point doesn't matter",
         problem=r"Use the graph of $f$ to find $f(2)$ and $\displaystyle\lim_{x\to2} f(x)$.",
         pre="ga, gl = plot_axes([-0.5, 4.5, 1], [-0.5, 6, 1], w=5, h=4.2)\n"
             "gfig = VGroup(ga, gl, ga.plot(lambda x: 0.5 * (x - 2) ** 2 + 3, x_range=[-0.5, 4.5], color=FUNC, stroke_width=4), open_dot(ga, 2, 3), closed_dot(ga, 2, 1, FUNC))",
         steps=[r"f(2) = 1 \ \ (\text{the filled dot})", r"\lim_{x\to2} f(x) = 3 \ \ (\text{where the graph is heading})"], at=[1, 2],
         extra=r'figure=gfig, text=r"Use the graph of $f$ above to find $f(2)$ and \[ \lim_{x\to2} f(x). \]"',
         lines=["Use the graph of f to find f of two, and the limit of f of x as x approaches two. [try it]",
                "f of two is the filled dot: one.",
                "As x approaches two from both sides, the graph heads to the hole at height three. So the limit is three, even though f of two is one. [long pause]"],
         screen="A parabola-shaped graph with a hole at (2, 3) and a filled dot at (2, 1). f(2) = 1 is marked at the dot; the limit 3 is marked at the hole.",
         work="2.2cm"),
    dict(num="1.2", title="Symbols to words", after="The notation",
         problem=r"$T(t)$ is the temperature in degrees Fahrenheit $t$ hours after noon. Explain the meaning of $\displaystyle\lim_{t\to3} T(t) = 72$.",
         steps=[r"\text{input: } t \to 3 \ \ (\text{the time approaches 3 PM})", r"\text{output: } T(t) \to 72 \ \ (\text{the temperature approaches } 72^\circ\text{F})",
                r"TEXT:As the time gets closer and closer to 3 PM, the temperature gets closer and closer to $72^\circ$F."], at=[1, 1, 2],
         lines=["T of t is the temperature in degrees Fahrenheit, t hours after noon. What does the limit of T of t, as t approaches three, equals seventy-two mean? [try it]",
                "Read the input, then the output. t approaching three means the time approaches three PM. T approaching seventy-two means the temperature approaches seventy-two degrees.",
                "So: as the time gets closer and closer to three PM, the temperature gets closer and closer to seventy-two degrees. [long pause]"],
         screen="The limit statement, with the input part and the output part each translated into words, then the full sentence.",
         work="2cm"),
    dict(num="1.2", title="Words to symbols", after="Symbols to words",
         problem=r"Write in limit notation: ``As $x$ approaches $-2$ from the left, $h(x)$ approaches $7$.''",
         steps=[r"\text{from the left: } x \to -2^-", r"\lim_{x\to -2^-} h(x) = 7"], at=[1, 2],
         lines=["Now the other direction. Write this in limit notation: as x approaches negative two from the left, h of x approaches seven. [try it]",
                "From the left means a small minus sign up and to the right of the negative two.",
                "So it's the limit, as x approaches negative two from the left, of h of x, equals seven. [long pause]"],
         screen="The sentence, then x → −2⁻ with the superscript minus circled, then the full limit statement.",
         work="1.6cm"),
    # ------------------------------------------------------------------ 1.4
    dict(num="1.4", title="Your own table", after="What makes a good table",
         problem=r"Use a table to estimate $\displaystyle\lim_{x\to1}\frac{x^3 - 1}{x - 1}$.",
         pre='own = table(["x", "0.9", "0.99", "0.999", "1.001", "1.01", "1.1"], [["f(x)", "2.71", "2.9701", "2.997", "3.003", "3.0301", "3.31"]], size=30)',
         steps=[r"\text{left: } 2.71,\ 2.9701,\ 2.997", r"\text{right: } 3.31,\ 3.0301,\ 3.003", r"\lim_{x\to1}\frac{x^3 - 1}{x - 1} \approx 3"], at=[1, 2, 3],
         extra="figure=own",
         lines=["Use a table to estimate the limit of x cubed minus one, over x minus one, as x approaches one. [try it]",
                "From the left, try point nine, point nine nine, and point nine nine nine. The outputs are two point seven one, two point nine seven, two point nine nine seven.",
                "From the right, one point one, one point zero one, one point zero zero one: three point three one, three point zero three, three point zero zero three. [pause]",
                "Both sides close in on three. [long pause]"],
         screen="A table with x = 0.9, 0.99, 0.999 on the left of 1 and 1.001, 1.01, 1.1 on the right, outputs filling in toward 3 from both sides.",
         checks=["limit((x**3 - 1)/(x - 1), x, 1) == 3"], work="3cm"),
    # ------------------------------------------------------------------ 1.5
    dict(num="1.5", title="Using given limits", after="Composite functions",
         problem=r"Suppose $\displaystyle\lim_{x\to4} f(x) = 3$ and $\displaystyle\lim_{x\to4} g(x) = -2$. Find the limit as $x \to 4$ of (a) $2f(x) - g(x)$, (b) $f(x)g(x)$, (c) $\dfrac{f(x)}{g(x)}$, (d) $\left[f(x)\right]^2 + g(x)$, (e) $\sqrt{f(x) + 6}$.",
         steps=[r"\text{(a) } \lim_{x\to4}\left[2f(x) - g(x)\right] = 2(3) - (-2) = 8", r"\text{(b) } \lim_{x\to4} f(x)g(x) = 3(-2) = -6",
                r"\text{(c) } \lim_{x\to4}\frac{f(x)}{g(x)} = \frac{3}{-2} = -\frac32", r"\text{(d) } \lim_{x\to4}\left(\left[f(x)\right]^2 + g(x)\right) = 3^2 + (-2) = 7",
                r"\text{(e) } \lim_{x\to4}\sqrt{f(x) + 6} = \sqrt{3 + 6} = 3"], at=[1, 2, 3, 4, 5],
         lines=["The limit of f is three, and the limit of g is negative two, as x approaches four. Find five limits built from them. [try it]",
                "The laws let us work with the limits like numbers. Two f minus g: two times three, minus negative two. Eight.",
                "f times g: three times negative two. Negative six. [pause]",
                "f over g: three over negative two, since the bottom limit isn't zero. Negative three halves.",
                "f squared plus g: nine plus negative two. Seven. [pause]",
                "And the square root of f plus six uses the composite rule: the square root of three plus six, which is three. [long pause]"],
         screen="The two given limits, then each of the five parts worked on its own line with limit notation.",
         work="3.2cm"),
    dict(num="1.5", title="Plug in", after="Direct substitution",
         problem=r"Find (a) $\displaystyle\lim_{x\to2}(x^3 - 4x + 1)$ and (b) $\displaystyle\lim_{x\to-1}\frac{x^2 + 3}{x - 2}$.",
         steps=[r"\text{(a) } \lim_{x\to2}(x^3 - 4x + 1) = 8 - 8 + 1 = 1", r"\text{(b) } x - 2 \to -3 \ne 0", r"\lim_{x\to-1}\frac{x^2 + 3}{x - 2} = \frac{4}{-3} = -\frac43"],
         at=[1, 2, 3],
         lines=["Find the limit of x cubed minus four x plus one as x approaches two, and the limit of x squared plus three over x minus two, as x approaches negative one. [try it]",
                "The first is a polynomial, so plug in: eight minus eight plus one. One.",
                "The second is a fraction. Check the bottom first: negative one minus two is negative three, not zero. [pause]",
                "So we can substitute: four over negative three. Negative four thirds. [long pause]"],
         screen="Each limit evaluated by direct substitution, with the denominator checked first in part (b).",
         checks=["limit((x**2 + 3)/(x - 2), x, -1) == Rational(-4, 3)"], work="2.4cm"),
]

if __name__ == "__main__" and len(sys.argv) == 1:
    apply(SPECS)

SPECS2 = [
    # ------------------------------------------------------------------ 1.6
    dict(num="1.6", title="Factor", after="Tool one: factor and cancel",
         problem=r"Find $\displaystyle\lim_{x\to2}\frac{x^3 - 8}{x - 2}$.",
         steps=[r"\text{plug in: } \frac{0}{0}", r"\lim_{x\to2}\frac{x^3 - 8}{x - 2} = \lim_{x\to2}\frac{\cancel{(x - 2)}(x^2 + 2x + 4)}{\cancel{x - 2}}",
                r"= \lim_{x\to2}(x^2 + 2x + 4) = 4 + 4 + 4 = 12"], at=[1, 2, 3],
         lines=["Find the limit of x cubed minus eight, over x minus two, as x approaches two. [try it]",
                "Plugging in gives zero over zero, so there's a common factor to find.",
                "x cubed minus eight is a difference of cubes: x minus two, times x squared plus two x plus four. The x minus two cancels. [pause]",
                "Now plug in: four plus four plus four. Twelve. [long pause]"],
         screen="The limit, the 0/0 check, the difference-of-cubes factoring with x − 2 struck out top and bottom, and the result 12.",
         checks=["limit((x**3 - 8)/(x - 2), x, 2) == 12"], work="2.6cm"),
    dict(num="1.6", title="Conjugate", after="Tool two: the conjugate",
         problem=r"Find $\displaystyle\lim_{x\to0}\frac{\sqrt{x + 4} - 2}{x}$.",
         steps=[r"\lim_{x\to0}\frac{\sqrt{x + 4} - 2}{x}\cdot\frac{\sqrt{x + 4} + 2}{\sqrt{x + 4} + 2}", r"= \lim_{x\to0}\frac{(x + 4) - 4}{x\left(\sqrt{x + 4} + 2\right)}",
                r"= \lim_{x\to0}\frac{\cancel{x}}{\cancel{x}\left(\sqrt{x + 4} + 2\right)}", r"= \lim_{x\to0}\frac{1}{\sqrt{x + 4} + 2} = \frac14"], at=[1, 2, 3, 4],
         lines=["Find the limit of the square root of x plus four, minus two, all over x, as x approaches zero. [try it]",
                "Zero over zero, and there's a root minus a number on top. Multiply top and bottom by the conjugate, root x plus four, plus two.",
                "On top, the square root squared is x plus four, minus four. That's just x. [pause]",
                "The x on top cancels the x on the bottom.",
                "Now plug in: one over two plus two. One fourth. [long pause]"],
         screen="The limit, multiplied by the conjugate over itself, the top simplifying to x, the x's struck out, and 1/4.",
         checks=["limit((sqrt(x + 4) - 2)/x, x, 0) == Rational(1, 4)"], work="2.8cm"),
    dict(num="1.6", title="Combine fractions", after="Tool three: clear the fractions",
         problem=r"Find $\displaystyle\lim_{x\to3}\frac{\frac1x - \frac13}{x - 3}$.",
         steps=[r"\lim_{x\to3}\frac{\frac1x - \frac13}{x - 3} = \lim_{x\to3}\frac{\frac{3 - x}{3x}}{x - 3}", r"= \lim_{x\to3}\frac{-\cancel{(x - 3)}}{3x\cancel{(x - 3)}}",
                r"= \lim_{x\to3}\left(-\frac{1}{3x}\right) = -\frac19"], at=[1, 2, 3],
         lines=["Find the limit of one over x minus one third, all over x minus three, as x approaches three. [try it]",
                "Combine the fractions on top over the common denominator three x: three minus x, over three x.",
                "Three minus x is the negative of x minus three, so the x minus three cancels. [pause]",
                "What's left is negative one over three x. At three, that's negative one ninth. [long pause]"],
         screen="The complex fraction combined into one fraction, the x − 3 factors struck out, and −1/9.",
         checks=["limit((1/x - Rational(1, 3))/(x - 3), x, 3) == Rational(-1, 9)"], work="2.8cm"),
    dict(num="1.6", title="Identity", after="Tool four, in a limit",
         problem=r"Find $\displaystyle\lim_{x\to0}\frac{\sin^2 x}{1 - \cos x}$.",
         steps=[r"\sin^2 x = 1 - \cos^2 x", r"\lim_{x\to0}\frac{1 - \cos^2 x}{1 - \cos x} = \lim_{x\to0}\frac{\cancel{(1 - \cos x)}(1 + \cos x)}{\cancel{1 - \cos x}}",
                r"= \lim_{x\to0}(1 + \cos x) = 2"], at=[1, 2, 3],
         lines=["Find the limit of sine squared x, over one minus cosine x, as x approaches zero. [try it]",
                "Zero over zero. Use the Pythagorean identity to write sine squared as one minus cosine squared.",
                "That's a difference of squares: one minus cosine, times one plus cosine. The one minus cosine cancels. [pause]",
                "Plug in: one plus one. Two. [long pause]"],
         screen="The Pythagorean identity rewriting sin² x, the difference of squares factored, the common factor struck out, and 2.",
         checks=["limit(sin(x)**2/(1 - cos(x)), x, 0) == 2"], work="2.6cm"),
    # ------------------------------------------------------------------ 1.7
    dict(num="1.7", title="Signs near a zero denominator", after="When you get nonzero over zero",
         problem=r"Find (a) $\displaystyle\lim_{x\to2}\frac{x + 1}{(x - 2)^2}$ and (b) $\displaystyle\lim_{x\to2}\frac{x + 1}{x - 2}$.",
         steps=[r"\text{(a) } \frac{3}{0}: \ (x - 2)^2 > 0 \text{ on both sides}", r"\lim_{x\to2}\frac{x + 1}{(x - 2)^2} = \infty",
                r"\text{(b) } \lim_{x\to2^-}\frac{x + 1}{x - 2} = -\infty, \quad \lim_{x\to2^+}\frac{x + 1}{x - 2} = \infty", r"\text{the limit does not exist}"],
         at=[1, 2, 3, 4],
         lines=["Find the limit as x approaches two of x plus one over x minus two squared, and of x plus one over x minus two. [try it]",
                "Both give three over zero, so check signs. In the first, x minus two squared is positive on both sides.",
                "So both one-sided limits are positive infinity, and the limit is infinity. [pause]",
                "In the second, x minus two is negative on the left and positive on the right: negative infinity from the left, infinity from the right.",
                "The sides disagree, so that limit does not exist. [long pause]"],
         screen="Each limit with its 3/0 check, the sign of the denominator on each side of 2, and the conclusions ∞ and DNE.",
         work="3cm"),
    dict(num="1.7", title="Absolute value", after="Absolute values and pieces",
         problem=r"Find $\displaystyle\lim_{x\to2}\frac{|x - 2|}{x - 2}$.",
         steps=[r"\lim_{x\to2^-}\frac{|x - 2|}{x - 2} = \lim_{x\to2^-}\frac{-(x - 2)}{x - 2} = -1", r"\lim_{x\to2^+}\frac{|x - 2|}{x - 2} = \lim_{x\to2^+}\frac{x - 2}{x - 2} = 1",
                r"\text{the sides disagree: the limit does not exist}"], at=[1, 2, 3],
         lines=["Find the limit of the absolute value of x minus two, over x minus two, as x approaches two. [try it]",
                "From the left, x minus two is negative, so its absolute value is the negative of x minus two. The ratio is negative one.",
                "From the right, x minus two is positive, and the ratio is one. [pause]",
                "Negative one and one disagree, so the limit does not exist. [long pause]"],
         screen="The left-hand and right-hand limits worked separately, giving −1 and 1, then 'does not exist.'",
         work="2.4cm"),
    dict(num="1.7", title="Two tools in one", after="Working through one",
         problem=r"Find $\displaystyle\lim_{x\to-4}\frac{x^2 + 2x - 8}{\sqrt{x + 5} - 1}$.",
         steps=[r"\lim_{x\to-4}\frac{(x + 4)(x - 2)}{\sqrt{x + 5} - 1}\cdot\frac{\sqrt{x + 5} + 1}{\sqrt{x + 5} + 1}",
                r"= \lim_{x\to-4}\frac{\cancel{(x + 4)}(x - 2)\left(\sqrt{x + 5} + 1\right)}{\cancel{x + 4}}", r"= \lim_{x\to-4}(x - 2)\left(\sqrt{x + 5} + 1\right) = (-6)(2) = -12"],
         at=[1, 2, 3],
         lines=["Find the limit of x squared plus two x minus eight, over the square root of x plus five, minus one, as x approaches negative four. [try it]",
                "Zero over zero. Factor the top into x plus four times x minus two, and multiply by the conjugate of the bottom.",
                "The bottom becomes x plus five minus one, which is x plus four. It cancels with the top. [pause]",
                "Plug in: negative six times two. Negative twelve. [long pause]"],
         screen="Factoring the top and multiplying by the conjugate, the x + 4 factors struck out, and −12.",
         checks=["limit((x**2 + 2*x - 8)/(sqrt(x + 5) - 1), x, -4) == -12"], work="3.4cm"),
    # ------------------------------------------------------------------ 1.8
    dict(num="1.8", title="Match the angle", after="The squeeze closes",
         problem=r"Find $\displaystyle\lim_{x\to0}\frac{\sin(5x)}{x}$.",
         steps=[r"\lim_{x\to0}\frac{\sin 5x}{x} = \lim_{x\to0} 5\cdot\frac{\sin 5x}{5x}", r"u = 5x \to 0: \quad \frac{\sin u}{u} \to 1", r"= 5 \cdot 1 = 5"], at=[1, 2, 3],
         lines=["Find the limit of sine five x over x, as x approaches zero. [try it]",
                "The special limit needs the same thing inside the sine and on the bottom. So multiply top and bottom by five: five times sine five x over five x.",
                "As x goes to zero, the angle five x goes to zero too, so sine five x over five x goes to one. [pause]",
                "The limit is five times one: five. [long pause]"],
         screen="The limit rewritten as 5 · sin(5x)/(5x), with the matching angles highlighted, then 5 · 1 = 5.",
         checks=["limit(sin(5*x)/x, x, 0) == 5"], work="2.6cm"),
    dict(num="1.8", title="Rewrite first", after="Match the angle",
         problem=r"Find $\displaystyle\lim_{x\to0}\frac{\tan x}{x}$.",
         steps=[r"\lim_{x\to0}\frac{\tan x}{x} = \lim_{x\to0}\frac{\sin x}{x}\cdot\frac{1}{\cos x}", r"= 1 \cdot \frac{1}{1} = 1"], at=[1, 2],
         lines=["Find the limit of tangent x over x, as x approaches zero. [try it]",
                "Rewrite tangent as sine over cosine: sine x over x, times one over cosine x. [pause]",
                "The first factor goes to one, and cosine of zero is one. So the limit is one. [long pause]"],
         screen="tan x rewritten as sin x / cos x, split into two factors, and 1 · 1 = 1.",
         checks=["limit(tan(x)/x, x, 0) == 1"], work="2.4cm"),
    dict(num="1.8", title="Squeeze with a bounded factor", after="Rewrite first",
         problem=r"Find $\displaystyle\lim_{x\to0} x\cos\frac{1}{x^2}$.",
         steps=[r"-1 \le \cos\frac{1}{x^2} \le 1", r"-|x| \le x\cos\frac{1}{x^2} \le |x|", r"\lim_{x\to0}(-|x|) = \lim_{x\to0}|x| = 0",
                r"\lim_{x\to0} x\cos\frac{1}{x^2} = 0"], at=[1, 2, 3, 4],
         lines=["Find the limit of x times cosine of one over x squared, as x approaches zero. [try it]",
                "Cosine of anything is between negative one and one.",
                "Multiply by x, using absolute values so the inequality works for negative x too: x cosine one over x squared is between negative absolute x and absolute x. [pause]",
                "Both bounds go to zero as x goes to zero.",
                "So by the squeeze theorem, the limit is zero. [long pause]"],
         screen="The bound on cosine, the squeeze −|x| ≤ x cos(1/x²) ≤ |x|, both bounds going to 0, and the conclusion.",
         work="2.4cm"),
    # ------------------------------------------------------------------ 1.9
    dict(num="1.9", title="Table meets formula", after="Checking with a table",
         problem=r"Values of $k$ near $x = 1$ are in the table. Assuming the pattern continues, find $\displaystyle\lim_{x\to1}\left[3k(x) - x^2\right]$.",
         pre='ktab = table(["x", "0.9", "0.99", "1.01", "1.1"], [["k(x)", "1.8", "1.98", "2.02", "2.2"]], size=38)',
         steps=[r"\lim_{x\to1} k(x) = 2 \ \ (\text{from the table})", r"\lim_{x\to1}\left[3k(x) - x^2\right] = 3(2) - 1^2 = 5"], at=[1, 2],
         extra=r'''figure=ktab, text=r"Values of $k$ near $x = 1$ are shown. \par\smallskip\centerline{\begin{tabular}{c|cccc} $x$ & 0.9 & 0.99 & 1.01 & 1.1 \\ \hline $k(x)$ & 1.8 & 1.98 & 2.02 & 2.2\end{tabular}} \par Assuming the pattern continues, find \[ \lim_{x\to1}\left[3k(x) - x^2\right]. \]"''',
         lines=["Values of k near x equals one are in the table. Find the limit of three k of x minus x squared, as x approaches one. [try it]",
                "From both sides, the table's outputs close in on two. So the limit of k is two. [pause]",
                "The limit laws do the rest: three times two, minus one squared. Five. [long pause]"],
         screen="The table of k values approaching 2 from both sides, then the limit laws giving 3(2) − 1 = 5.",
         work="2.4cm"),
    # ------------------------------------------------------------------ 1.10
    dict(num="1.10", title="Where the pieces meet", after="Piecewise functions",
         problem=r"Let $f(x) = \begin{cases} x + 1, & x < 1 \\ x^2, & x \ge 1 \end{cases}$. Is $f$ continuous at $x = 1$? If not, classify the discontinuity.",
         steps=[r"\lim_{x\to1^-}(x + 1) = 2", r"\lim_{x\to1^+}x^2 = 1", r"\text{the one-sided limits differ: a jump discontinuity}"], at=[1, 2, 3],
         lines=["Is this piecewise function continuous at one? If not, what kind of discontinuity is it? [try it]",
                "From the left, the piece x plus one heads to two.",
                "From the right, the piece x squared heads to one. [pause]",
                "The one-sided limits disagree, so the graph jumps: a jump discontinuity. [long pause]"],
         screen="The two pieces, the left-hand limit 2 and the right-hand limit 1, and the verdict 'jump.'",
         work="2.2cm"),
    # ------------------------------------------------------------------ 1.11
    dict(num="1.11", title="Justify continuity", after="A justification, written out",
         problem=r"Let $f(x) = \begin{cases} x^2 + 1, & x < 2 \\ 4x - 3, & x \ge 2 \end{cases}$. Is $f$ continuous at $x = 2$? Justify using the definition.",
         steps=[r"f(2) = 4(2) - 3 = 5", r"\lim_{x\to2^-}(x^2 + 1) = 5, \quad \lim_{x\to2^+}(4x - 3) = 5 \ \Rightarrow\ \lim_{x\to2} f(x) = 5",
                r"\lim_{x\to2} f(x) = f(2): \ f \text{ is continuous at } x = 2"], at=[1, 2, 3],
         lines=["Is this function continuous at two? Justify your answer using the definition. [try it]",
                "Condition one: f of two exists. It's four times two minus three, which is five.",
                "Condition two: the limit exists. From the left it's two squared plus one, five, and from the right it's five too. [pause]",
                "Condition three: the limit equals the value. Five equals five, so f is continuous at two. [long pause]"],
         screen="The three conditions checked one at a time, each with its value, ending with lim f(x) = f(2).",
         work="3.6cm"),
    dict(num="1.11", title="Justify discontinuity", after="Justify continuity",
         problem=r"Let $g(x) = \begin{cases} \dfrac{x^2 - 9}{x - 3}, & x \ne 3 \\ 5, & x = 3 \end{cases}$. Is $g$ continuous at $x = 3$?",
         steps=[r"g(3) = 5", r"x \ne 3: \ g(x) = \frac{\cancel{(x - 3)}(x + 3)}{\cancel{x - 3}} = x + 3", r"\lim_{x\to3} g(x) = 6 \ne 5 = g(3)", r"g \text{ is not continuous at } x = 3"],
         at=[1, 2, 3, 3],
         lines=["Now g: x squared minus nine over x minus three, except that g of three is five. Is g continuous at three? [try it]",
                "g of three is five.",
                "Away from three, the fraction simplifies: x minus three cancels, leaving x plus three. [pause]",
                "So the limit as x approaches three is six. Six isn't five, so g is not continuous at three. [long pause]"],
         screen="g(3) = 5, the fraction factored with x − 3 struck out, the limit 6, and 6 ≠ 5.",
         work="3cm"),
    # ------------------------------------------------------------------ 1.12
    dict(num="1.12", title="Read the domain", after="Reading a domain",
         problem=r"Where is $f(x) = \dfrac{\sqrt{x - 1}}{x - 4}$ continuous?",
         steps=[r"\sqrt{x - 1}: \ x \ge 1", r"x - 4 \ne 0: \ x \ne 4", r"\text{continuous on } [1, 4) \cup (4, \infty)"], at=[1, 2, 3],
         lines=["Where is the square root of x minus one, over x minus four, continuous? [try it]",
                "The square root needs x minus one to be at least zero, so x is at least one.",
                "The denominator can't be zero, so x isn't four. [pause]",
                "So f is continuous on one to four, including one, and on four to infinity. [long pause]"],
         screen="The root's condition, the denominator's condition, and the domain written as intervals.",
         work="2.8cm"),
    dict(num="1.12", title="Logs and trig", after="Read the domain",
         problem=r"Where are (a) $g(x) = \ln(9 - x^2)$ and (b) $h(x) = \tan x$ continuous?",
         steps=[r"\text{(a) } 9 - x^2 > 0 \ \Rightarrow\ -3 < x < 3", r"\text{(b) } \tan x = \frac{\sin x}{\cos x}: \ \cos x \ne 0", r"x \ne \frac{\pi}{2} + k\pi"], at=[1, 2, 3],
         lines=["Where are the natural log of nine minus x squared, and tangent x, continuous? [try it]",
                "A log needs a positive input: nine minus x squared greater than zero, so x is between negative three and three.",
                "Tangent is sine over cosine, so it's continuous wherever cosine isn't zero. [pause]",
                "Cosine is zero at pi over two plus any multiple of pi. Everywhere else, tangent is continuous. [long pause]"],
         screen="The log's condition giving (−3, 3); tan x as sin x / cos x, and the excluded points π/2 + kπ.",
         work="2.8cm"),
    # ------------------------------------------------------------------ 1.13
    dict(num="1.13", title="Two seams", after="Two unknowns, two seams", notes_title="Two seams, two unknowns",
         problem=r"Find $a$ and $b$ so that $f(x) = \begin{cases} x + a, & x < -1 \\ bx^2 + 1, & -1 \le x \le 2 \\ 3x - 1, & x > 2 \end{cases}$ is continuous everywhere.",
         steps=[r"x = 2: \ 4b + 1 = 3(2) - 1 = 5 \ \Rightarrow\ b = 1", r"x = -1: \ -1 + a = b(-1)^2 + 1 = 2", r"a = 3"], at=[1, 2, 3],
         lines=["Find a and b so that this three-piece function is continuous everywhere. [try it]",
                "Start at the seam with only one unknown, x equals two. The middle piece gives four b plus one, and the right piece gives five. So b is one.",
                "Now the seam at negative one. The left piece gives negative one plus a, and the middle piece gives b plus one, which is two. [pause]",
                "So a is three. [long pause]"],
         screen="The three-piece function, the seam at x = 2 solved first for b, then the seam at x = −1 for a.",
         work="3.4cm"),
    # ------------------------------------------------------------------ 1.14
    dict(num="1.14", title="A sign chart", after="Finding the sign",
         problem=r"Let $f(x) = \dfrac{x + 3}{(x - 1)(x + 2)}$. Find $\displaystyle\lim_{x\to1^-} f(x)$ and $\displaystyle\lim_{x\to1^+} f(x)$.",
         steps=[r"\text{near } x = 1: \ x + 3 \approx 4 > 0, \quad x + 2 \approx 3 > 0", r"\text{left: } \frac{(+)}{(-)(+)} = - \ \Rightarrow\ \lim_{x\to1^-} f(x) = -\infty",
                r"\text{right: } \frac{(+)}{(+)(+)} = + \ \Rightarrow\ \lim_{x\to1^+} f(x) = \infty"], at=[1, 2, 3],
         lines=["Find the one-sided limits of x plus three, over x minus one times x plus two, as x approaches one. [try it]",
                "Near one, x plus three is about four, and x plus two is about three. Both positive.",
                "On the left, x minus one is a small negative number. Plus over negative times plus is negative, so the limit is negative infinity. [pause]",
                "On the right, x minus one is a small positive number, everything is positive, and the limit is infinity. [long pause]"],
         screen="The sign of each factor near x = 1, written as a fraction of signs for each side, and the two infinite limits.",
         work="3cm"),
    # ------------------------------------------------------------------ 1.15
    dict(num="1.15", title="Roots at negative infinity", after="Other functions",
         problem=r"Find $\displaystyle\lim_{x\to-\infty}\frac{\sqrt{4x^2 + 1}}{x}$.",
         steps=[r"\text{leading terms: } \frac{\sqrt{4x^2}}{x} = \frac{2|x|}{x}", r"x < 0: \ |x| = -x", r"\lim_{x\to-\infty}\frac{\sqrt{4x^2 + 1}}{x} = \lim_{x\to-\infty}\frac{2(-x)}{x} = -2"],
         at=[1, 2, 3],
         lines=["Find the limit of the square root of four x squared plus one, over x, as x goes to negative infinity. [try it]",
                "The fastest-growing terms dominate: the root of four x squared on top, which is two times the absolute value of x, and x on the bottom.",
                "Here's the catch. For negative x, the absolute value of x is negative x. [pause]",
                "So the ratio is two times negative x, over x: negative two. [long pause]"],
         screen="The leading terms, the absolute value rewritten as −x for negative x, and the limit −2.",
         checks=["limit(sqrt(4*x**2 + 1)/x, x, -oo) == -2"], work="3cm"),
    # ------------------------------------------------------------------ 1.16
    dict(num="1.16", title="A root exists", after="Finding a root",
         problem=r"Show that $x^3 + x - 1 = 0$ has a solution between $x = 0$ and $x = 1$.",
         steps=[r"f(x) = x^3 + x - 1 \text{ is a polynomial: continuous on } [0, 1]", r"f(0) = -1 < 0 < 1 = f(1)", r"\text{IVT: } f(c) = 0 \text{ for some } c \text{ in } (0, 1)"],
         at=[1, 2, 3],
         lines=["Show that x cubed plus x minus one equals zero has a solution between zero and one. [try it]",
                "Call the left side f. It's a polynomial, so it's continuous on zero to one. That's the condition the theorem needs.",
                "f of zero is negative one, and f of one is one. Zero is between them. [pause]",
                "So by the Intermediate Value Theorem, f of c equals zero for some c between zero and one. [long pause]"],
         screen="The continuity statement, the two endpoint values with 0 between them, and the IVT conclusion.",
         work="3cm"),
    dict(num="1.16", title="A given value", after="A root exists",
         problem=r"Show that $\cos x = x$ for some $x$ in $\left[0, \dfrac\pi2\right]$.",
         steps=[r"g(x) = \cos x - x \text{ is continuous on } \left[0, \tfrac\pi2\right]", r"g(0) = 1 > 0, \quad g\left(\tfrac\pi2\right) = -\tfrac\pi2 < 0",
                r"\text{IVT: } g(c) = 0, \text{ so } \cos c = c"], at=[1, 2, 3],
         lines=["Show that cosine x equals x for some x between zero and pi over two. [try it]",
                "Turn it into a root problem: let g of x be cosine x minus x. It's continuous on the interval.",
                "g of zero is one, which is positive. g of pi over two is negative pi over two, which is negative. [pause]",
                "By the Intermediate Value Theorem, g of c is zero somewhere in between, and there cosine c equals c. [long pause]"],
         screen="g(x) = cos x − x defined and stated continuous, its values at 0 and π/2 with opposite signs, and the IVT conclusion.",
         work="3cm"),
]

if __name__ == "__main__" and len(sys.argv) > 1 and sys.argv[1] == "2":
    apply(SPECS2)
