"""Units 4-5 notes examples moved into the videos (2026-10-01). Run once: python tools/specs_unit45.py"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from add_video_example import apply  # noqa: E402

SPECS = [
    dict(num="4.1", title="Draining a tank", after="The sentence",
         problem=r"$W(t)$ is the number of liters of water in a tank $t$ minutes after a drain opens. Interpret $W'(5) = -3$.",
         steps=[r"\text{when: } t = 5 \text{ minutes}", r"\text{what: the amount of water;} \quad \text{which way: } -3 < 0, \text{ decreasing}",
                r"\text{how fast: } 3 \text{ liters per minute}", r"TEXT:At $t = 5$ minutes, the amount of water in the tank is decreasing at a rate of $3$ liters per minute."],
         at=[1, 1, 2, 3],
         lines=["W of t is the liters of water in a tank, t minutes after a drain opens. Interpret W prime of five equals negative three. [try it]",
                "Fill the slots. When: at five minutes. What: the amount of water. Which way: negative means decreasing.",
                "How fast: three liters per minute. [pause]",
                "So: at t equals five minutes, the amount of water in the tank is decreasing at a rate of three liters per minute. [long pause]"],
         screen="The four slots of the sentence filled in one at a time, then the full sentence.", work="2.2cm"),
    dict(num="4.4", title="A growing square", after="Differentiate first, then substitute",
         problem=r"The side $s$ of a square grows at $3$ cm/s. How fast is its area $A = s^2$ growing when $s = 4$ cm?",
         steps=[r"A = s^2 \ \Rightarrow\ \frac{dA}{dt} = 2s\,\frac{ds}{dt}", r"= 2(4)(3) = 24 \text{ cm}^2\text{/s}"], at=[1, 2],
         lines=["The side of a square grows at three centimeters per second. How fast is the area growing when the side is four? [try it]",
                "Differentiate A equals s squared with respect to t: d A d t is two s d s d t. [pause]",
                "Now substitute: two times four times three. Twenty-four square centimeters per second. [long pause]"],
         screen="A = s² differentiated with respect to t, then the values substituted.",
         checks=["2*4*3 == 24"], work="2.2cm"),
    dict(num="4.5", title="A shadow", after="Eliminate first",
         problem=r"Ana, who is $5$ ft tall, walks away from a $15$-ft lamppost at $4$ ft/s. How fast is her shadow lengthening?",
         steps=[r"\frac{15}{x + s} = \frac{5}{s} \ \Rightarrow\ 15s = 5x + 5s", r"s = \frac{x}{2}", r"\frac{ds}{dt} = \frac12\,\frac{dx}{dt} = \frac12(4) = 2 \text{ ft/s}"],
         at=[1, 2, 3],
         lines=["Ana is five feet tall, and she walks away from a fifteen-foot lamppost at four feet per second. How fast is her shadow lengthening? [try it]",
                "Let x be her distance from the post and s her shadow's length. The big triangle and the small one are similar: fifteen over x plus s equals five over s.",
                "Cross-multiply and simplify: s equals x over two. [pause]",
                "Differentiate: d s d t is one half of d x d t, which is two feet per second, at every moment. [long pause]"],
         screen="The lamppost, Ana, and her shadow, with the two similar triangles; the proportion, s = x/2, and ds/dt = 2.",
         checks=["Rational(1, 2)*4 == 2"], work="3cm"),
    dict(num="4.6", title="Using given values", after="The tangent line as an estimate",
         problem=r"$f(4) = 10$ and $f'(4) = 2.5$. Estimate $f(4.2)$.",
         steps=[r"L(x) = 10 + 2.5(x - 4)", r"f(4.2) \approx L(4.2) = 10 + 2.5(0.2) = 10.5"], at=[1, 2],
         lines=["f of four is ten, and f prime of four is two and a half. Estimate f of four point two. [try it]",
                "The linearization at four is ten plus two point five times x minus four. [pause]",
                "At four point two: ten plus two point five times point two. Ten point five. [long pause]"],
         screen="L(x) built from the given point and slope, then evaluated at 4.2.",
         checks=["10 + Rational(5, 2)*Rational(1, 5) == Rational(21, 2)"], work="2cm"),
    dict(num="5.1", title="From given values", after="When it fails", notes_title="From a table",
         problem=r"$f$ is differentiable, $f(1) = 4$ and $f(5) = 12$. Must $f'(c) = 2$ for some $c$ in $(1, 5)$?",
         steps=[r"\text{differentiable} \Rightarrow \text{continuous on } [1, 5], \text{ differentiable on } (1, 5)", r"\frac{f(5) - f(1)}{5 - 1} = \frac{12 - 4}{4} = 2",
                r"\text{MVT: } f'(c) = 2 \text{ for some } c \text{ in } (1, 5)"], at=[1, 2, 3],
         lines=["f is differentiable, f of one is four, and f of five is twelve. Must f prime of c equal two somewhere between one and five? [try it]",
                "Check the conditions. Differentiable means continuous too, so both hold on the interval.",
                "The average rate of change: twelve minus four, over four. Two. [pause]",
                "So yes: by the Mean Value Theorem, f prime of c is two for some c between one and five. [long pause]"],
         screen="The two conditions checked, the average rate 2, and the MVT conclusion.", work="2.4cm"),
    dict(num="5.2", title="Find the critical points", after="Critical points",
         problem=r"Find the critical points of $f(x) = x^4 - 8x^2$.",
         steps=[r"f'(x) = 4x^3 - 16x = 4x(x - 2)(x + 2)", r"f'(x) = 0 \text{ at } x = -2,\ 0,\ 2", r"f' \text{ is never undefined}"], at=[1, 2, 3],
         lines=["Find the critical points of x to the fourth minus eight x squared. [try it]",
                "The derivative is four x cubed minus sixteen x. Factor: four x, times x minus two, times x plus two.",
                "That's zero at negative two, zero, and two. [pause]",
                "And a polynomial's derivative is never undefined, so those three are all the critical points. [long pause]"],
         screen="f′ factored completely, its zeros, and the note that f′ is never undefined.",
         checks=["solve(diff(x**4 - 8*x**2, x), x) == [-2, 0, 2]"], work="2.4cm"),
    dict(num="5.3", title="Increasing from a sign chart", after="A sign chart", notes_title="A quadratic's derivative",
         problem=r"Where is $f(x) = x^3 - 3x^2 + 4$ increasing?",
         steps=[r"f'(x) = 3x^2 - 6x = 3x(x - 2)", r"f'(-1) = 9 > 0, \quad f'(1) = -3 < 0, \quad f'(3) = 9 > 0", r"\text{increasing on } (-\infty, 0) \text{ and } (2, \infty)"],
         at=[1, 2, 3],
         lines=["Where is x cubed minus three x squared plus four increasing? [try it]",
                "f prime is three x squared minus six x, which factors as three x times x minus two. Critical points: zero and two.",
                "Test one value in each piece: f prime of negative one is nine, f prime of one is negative three, f prime of three is nine. [pause]",
                "So f is increasing on negative infinity to zero, and on two to infinity, because f prime is positive there. [long pause]"],
         screen="f′ factored, the test values in each piece with their signs, and the increasing intervals.",
         checks=["[diff(x**3 - 3*x**2 + 4, x).subs(x, v) for v in (-1, 1, 3)] == [9, -3, 9]"], work="3cm"),
    dict(num="5.4", title="From a sign chart", after="Write the reason",
         problem=r"$f'(x) = x(x - 4)^2$. Find and classify the critical points of $f$.",
         steps=[r"\text{critical points: } x = 0,\ x = 4", r"\text{signs of } f' \text{: } -,\ +,\ +", r"x = 0: \ - \text{ to } +, \text{ relative minimum}",
                r"x = 4: \ \text{no sign change, no extremum}"], at=[1, 2, 3, 4],
         lines=["f prime of x is x times x minus four squared. Find and classify the critical points of f. [try it]",
                "The critical points are zero and four.",
                "Signs of f prime: negative before zero, positive between zero and four, positive after four. The square keeps it positive. [pause]",
                "At zero, f prime changes from negative to positive: a relative minimum.",
                "At four, f prime doesn't change sign: no extremum. [long pause]"],
         screen="The sign chart of f′ with critical points 0 and 4, and each point classified with its reason.", work="3cm"),
    dict(num="5.5", title="A parabola on an interval", after="Don't skip the endpoints",
         problem=r"Find the absolute extrema of $f(x) = x^2 - 4x$ on $[0, 5]$.",
         steps=[r"f'(x) = 2x - 4 = 0 \text{ at } x = 2", r"f(0) = 0, \quad f(2) = -4, \quad f(5) = 5", r"\text{absolute max } 5 \text{ at } x = 5; \ \ \text{absolute min } -4 \text{ at } x = 2"],
         at=[1, 2, 3],
         lines=["Find the absolute extrema of x squared minus four x on zero to five. [try it]",
                "f prime is two x minus four, zero at two.",
                "The candidates: f of zero is zero, f of two is negative four, f of five is five. [pause]",
                "The absolute maximum is five, at the endpoint five. The absolute minimum is negative four, at two. [long pause]"],
         screen="The critical point, the table of three candidates, and the absolute max and min.", work="3cm"),
    dict(num="5.6", title="A cubic", after="Points of inflection",
         problem=r"Where is $f(x) = x^3 + 3x^2$ concave up? Find any points of inflection.",
         steps=[r"f'(x) = 3x^2 + 6x, \quad f''(x) = 6x + 6", r"f'' > 0 \text{ for } x > -1: \ \text{concave up on } (-1, \infty)", r"f'' < 0 \text{ for } x < -1: \ \text{concave down}",
                r"\text{inflection at } x = -1: \ \ (-1, 2)"], at=[1, 2, 3, 4],
         lines=["Where is x cubed plus three x squared concave up? Find any points of inflection. [try it]",
                "f prime is three x squared plus six x, and f double prime is six x plus six.",
                "f double prime is positive for x greater than negative one: concave up there. [pause]",
                "And negative for x less than negative one: concave down.",
                "It changes sign at negative one. f of negative one is negative one plus three, two. The inflection point is negative one, two. [long pause]"],
         screen="f″, its sign on each side of −1, the concavity intervals, and the inflection point.",
         checks=["(x**3 + 3*x**2).subs(x, -1) == 2"], work="2.6cm"),
    dict(num="5.7", title="Using the test", after="The test",
         problem=r"Classify the critical points of $f(x) = 2x^3 - 6x$.",
         steps=[r"f'(x) = 6x^2 - 6 = 0 \text{ at } x = \pm 1", r"f''(x) = 12x", r"f''(-1) = -12 < 0: \ \text{relative max}; \quad f''(1) = 12 > 0: \ \text{relative min}"],
         at=[1, 2, 3],
         lines=["Classify the critical points of two x cubed minus six x. [try it]",
                "f prime is six x squared minus six, zero at one and negative one.",
                "f double prime is twelve x. [pause]",
                "At negative one it's negative twelve: concave down, a relative maximum. At one it's twelve: concave up, a relative minimum. [long pause]"],
         screen="The critical points, f″, and the sign of f″ at each point with its classification.", work="2.6cm"),
    dict(num="5.8", title="Reading this graph", after="Reading the graph of f prime",
         problem=r"The graph of $f'(x) = \frac12(x + 2)(x - 1)(x - 3)$ is shown. Where does $f$ have a relative maximum? A relative minimum?",
         pre="ra, rl = plot_axes([-3, 4, 1], [-6, 6, 2], w=5, h=3.8, ylabel=\"f'(x)\")\n"
             "rfig = VGroup(ra, rl, ra.plot(lambda x: 0.5 * (x + 2) * (x - 1) * (x - 3), x_range=[-2.6, 3.7], color=DERIV, stroke_width=4))",
         steps=[r"x = 1: \ f' \text{ changes from } + \text{ to } -: \ \text{relative max}", r"x = -2,\ 3: \ f' \text{ changes from } - \text{ to } +: \ \text{relative min}"],
         at=[1, 2], extra="figure=rfig",
         lines=["Here's the graph of f prime, not f. Where does f have a relative maximum? A relative minimum? [try it]",
                "Look where f prime crosses the axis. At one, it goes from above to below: positive to negative. A relative maximum of f. [pause]",
                "At negative two and at three, it goes from below to above: relative minima. [long pause]"],
         screen="The graph of f′ with its three zeros marked; the crossing at x = 1 labeled 'max', the crossings at −2 and 3 labeled 'min'.",
         work="2.2cm"),
    dict(num="5.10", title="Setting up", after="One quantity, one variable",
         problem=r"A rectangle has perimeter $40$. Write its area as a function of its width $w$, and give the domain.",
         steps=[r"2w + 2\ell = 40 \ \Rightarrow\ \ell = 20 - w", r"A(w) = w(20 - w)", r"0 < w < 20"], at=[1, 2, 3],
         lines=["A rectangle has perimeter forty. Write its area as a function of its width w, and give the domain. [try it]",
                "The constraint: two w plus two l is forty, so l is twenty minus w.",
                "The area is w times l: w times twenty minus w. [pause]",
                "Both sides must be positive, so w is between zero and twenty. [long pause]"],
         screen="The constraint solved for ℓ, the area in one variable, and the domain.", work="2.6cm"),
    dict(num="5.11", title="Closest point", after="Justifying the answer",
         problem=r"Find the point on the line $y = x + 1$ closest to $(3, 0)$.",
         steps=[r"D^2 = (x - 3)^2 + (x + 1)^2", r"\frac{d}{dx}D^2 = 2(x - 3) + 2(x + 1) = 4x - 4 = 0 \text{ at } x = 1", r"(1, 2), \quad D = \sqrt{4 + 4} = 2\sqrt2"],
         at=[1, 2, 3],
         lines=["Find the point on the line y equals x plus one closest to three, zero. [try it]",
                "Minimize the square of the distance: x minus three squared, plus x plus one squared.",
                "Its derivative is two times x minus three plus two times x plus one: four x minus four. That's zero at one. [pause]",
                "The point is one, two, at a distance of two root two. [long pause]"],
         screen="D² written in one variable, its derivative set to 0, and the closest point.",
         checks=["solve(diff((x - 3)**2 + (x + 1)**2, x), x) == [1]"], work="2.8cm"),
]

if __name__ == "__main__":
    apply(SPECS)
