# Generated by Django 5.2.17 on 2026-09-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_full_access'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Set for class students: results wait for release', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='accounts.classroom'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='form',
            field=models.CharField(blank=True, help_text='Paper form letter for class attempts', max_length=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='served',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=8)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='accounts.classroom')),
            ],
            options={
                'unique_together': {('classroom', 'topic')},
            },
        ),
    ]
