# Generated by Django 5.2.17 on 2026-10-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=20)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('part', models.PositiveSmallIntegerField(default=0)),
                ('part_started', models.DateTimeField(blank=True, null=True)),
                ('timing', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=dict)),
                ('flags', models.JSONField(default=list)),
                ('frq', models.JSONField(default=dict)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('mc_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started'],
                'indexes': [models.Index(fields=['user', 'exam'], name='course_exam_user_id_ecaed8_idx')],
            },
        ),
    ]
