# Generated by Django 5.2.17 on 2026-09-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_access',
            field=models.BooleanField(default=False, help_text='Paid or granted access outside a class'),
        ),
    ]
